//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace 模板
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class ArticleEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“ArticleEntities”部分中的连接字符串初始化新 ArticleEntities 对象。
        /// </summary>
        public ArticleEntities() : base("name=ArticleEntities", "ArticleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ArticleEntities 对象。
        /// </summary>
        public ArticleEntities(string connectionString) : base(connectionString, "ArticleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ArticleEntities 对象。
        /// </summary>
        public ArticleEntities(EntityConnection connection) : base(connection, "ArticleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Articles> Articles
        {
            get
            {
                if ((_Articles == null))
                {
                    _Articles = base.CreateObjectSet<Articles>("Articles");
                }
                return _Articles;
            }
        }
        private ObjectSet<Articles> _Articles;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<pl> pl
        {
            get
            {
                if ((_pl == null))
                {
                    _pl = base.CreateObjectSet<pl>("pl");
                }
                return _pl;
            }
        }
        private ObjectSet<pl> _pl;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<User> User
        {
            get
            {
                if ((_User == null))
                {
                    _User = base.CreateObjectSet<User>("User");
                }
                return _User;
            }
        }
        private ObjectSet<User> _User;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Articles EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToArticles(Articles articles)
        {
            base.AddObject("Articles", articles);
        }
    
        /// <summary>
        /// 用于向 pl EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTopl(pl pl)
        {
            base.AddObject("pl", pl);
        }
    
        /// <summary>
        /// 用于向 User EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ArticleModel", Name="Articles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Articles : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Articles 对象。
        /// </summary>
        /// <param name="articleID">ArticleID 属性的初始值。</param>
        public static Articles CreateArticles(global::System.Int32 articleID)
        {
            Articles articles = new Articles();
            articles.ArticleID = articleID;
            return articles;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ArticleID
        {
            get
            {
                return _ArticleID;
            }
            set
            {
                if (_ArticleID != value)
                {
                    OnArticleIDChanging(value);
                    ReportPropertyChanging("ArticleID");
                    _ArticleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ArticleID");
                    OnArticleIDChanged();
                }
            }
        }
        private global::System.Int32 _ArticleID;
        partial void OnArticleIDChanging(global::System.Int32 value);
        partial void OnArticleIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ArticleTitle
        {
            get
            {
                return _ArticleTitle;
            }
            set
            {
                OnArticleTitleChanging(value);
                ReportPropertyChanging("ArticleTitle");
                _ArticleTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ArticleTitle");
                OnArticleTitleChanged();
            }
        }
        private global::System.String _ArticleTitle;
        partial void OnArticleTitleChanging(global::System.String value);
        partial void OnArticleTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ArticleContent
        {
            get
            {
                return _ArticleContent;
            }
            set
            {
                OnArticleContentChanging(value);
                ReportPropertyChanging("ArticleContent");
                _ArticleContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ArticleContent");
                OnArticleContentChanged();
            }
        }
        private global::System.String _ArticleContent;
        partial void OnArticleContentChanging(global::System.String value);
        partial void OnArticleContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Author
        {
            get
            {
                return _Author;
            }
            set
            {
                OnAuthorChanging(value);
                ReportPropertyChanging("Author");
                _Author = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Author");
                OnAuthorChanged();
            }
        }
        private global::System.String _Author;
        partial void OnAuthorChanging(global::System.String value);
        partial void OnAuthorChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ArticleModel", Name="pl")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class pl : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 pl 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="conten">conten 属性的初始值。</param>
        /// <param name="author">author 属性的初始值。</param>
        public static pl Createpl(global::System.Int32 id, global::System.String conten, global::System.String author)
        {
            pl pl = new pl();
            pl.id = id;
            pl.conten = conten;
            pl.author = author;
            return pl;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String conten
        {
            get
            {
                return _conten;
            }
            set
            {
                OncontenChanging(value);
                ReportPropertyChanging("conten");
                _conten = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("conten");
                OncontenChanged();
            }
        }
        private global::System.String _conten;
        partial void OncontenChanging(global::System.String value);
        partial void OncontenChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String author
        {
            get
            {
                return _author;
            }
            set
            {
                OnauthorChanging(value);
                ReportPropertyChanging("author");
                _author = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("author");
                OnauthorChanged();
            }
        }
        private global::System.String _author;
        partial void OnauthorChanging(global::System.String value);
        partial void OnauthorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String articleid
        {
            get
            {
                return _articleid;
            }
            set
            {
                OnarticleidChanging(value);
                ReportPropertyChanging("articleid");
                _articleid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("articleid");
                OnarticleidChanged();
            }
        }
        private global::System.String _articleid;
        partial void OnarticleidChanging(global::System.String value);
        partial void OnarticleidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sj
        {
            get
            {
                return _sj;
            }
            set
            {
                OnsjChanging(value);
                ReportPropertyChanging("sj");
                _sj = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sj");
                OnsjChanged();
            }
        }
        private global::System.String _sj;
        partial void OnsjChanging(global::System.String value);
        partial void OnsjChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ArticleModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 User 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static User CreateUser(global::System.Int32 id)
        {
            User user = new User();
            user.id = id;
            return user;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String psw
        {
            get
            {
                return _psw;
            }
            set
            {
                OnpswChanging(value);
                ReportPropertyChanging("psw");
                _psw = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("psw");
                OnpswChanged();
            }
        }
        private global::System.String _psw;
        partial void OnpswChanging(global::System.String value);
        partial void OnpswChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> score
        {
            get
            {
                return _score;
            }
            set
            {
                OnscoreChanging(value);
                ReportPropertyChanging("score");
                _score = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("score");
                OnscoreChanged();
            }
        }
        private Nullable<global::System.Int32> _score;
        partial void OnscoreChanging(Nullable<global::System.Int32> value);
        partial void OnscoreChanged();

        #endregion

    
    }

    #endregion

    
}
